version: "3.8"

services:
  domafleet-backend:
    build: .
    container_name: domafleet-backend
    ports:
      - "8446:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=https://api.domafleet.io,http://localhost:5173
      - DOMA_GRAPHQL_ENDPOINT=${DOMA_GRAPHQL_ENDPOINT:-https://api-testnet.doma.xyz/graphql}
      - DOMA_API_KEY=v1.b7ab822fd673775dc6d5a403198215c2de9614ee0b4757c4d1ef9bc1b7b8e59d
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backend/.env:/app/backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - domafleet-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.domafleet-backend.rule=Host(`api.domafleet.io`)"
      - "traefik.http.routers.domafleet-backend.entrypoints=websecure"
      - "traefik.http.routers.domafleet-backend.tls=true"
      - "traefik.http.routers.domafleet-backend.tls.certresolver=https-resolver"
      - "traefik.http.services.domafleet-backend.loadbalancer.server.port=3001"
      - "traefik.http.routers.domafleet-backend-http.rule=Host(`api.domafleet.io`)"
      - "traefik.http.routers.domafleet-backend-http.entrypoints=web"
      - "traefik.http.routers.domafleet-backend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.docker.network=traefik-network"

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: domafleet-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - domafleet-backend
    networks:
      - domafleet-network
    profiles:
      - with-nginx

volumes:
  domafleet_data:
    driver: local
  domafleet_logs:
    driver: local

networks:
  domafleet-network:
    driver: bridge
  traefik-network:
    external: true
    name: traefik-network
